### ISSUE TITLE
Can I ask  which code file contain SEMR computation?

### ISSUE THREAD

**Issue by georgezzzh** [allogn/robustness#1]
I read your paper that On the Robust under Node Attack. When I read the third page of this paper, I feel confuse about detail of  SEMR algorithm, so can I  ask for help which file  is SEMR Computation code? thank you.

**Comment by allogn** [comment]
Dear @georgezzzh, 

Thank you for your interest in our work. The class `Rob` in `src/SatGreedy/include/rob.h` is responsible for computing SEMR. The class has different modes, each mode corresponds to different ways of finding the maximum tree. The mode used in our paper is called `DYN_GRAIL_MAX_TREE`, so you may refer to lines 745-796 for the main SEMR procedure. The outline is: (1) bulid live edge graph (line 728); (2) incrementally add nodes to a dynamic index (dagger) derived from an adversarial strategy (line 766 adds a node, for example). tree_size corresponds to the EMR value for a particular number of blocked nodes. 

I hope this helps.
